services:
  nginx:
    container_name: nginx
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always